<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Análise Básica de Dados: Experimentos | R para Estudantes de Marketing</title>
  <meta name="description" content="Análise Básica de Dados: Experimentos | R para Estudantes de Marketing" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Análise Básica de Dados: Experimentos | R para Estudantes de Marketing" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Análise Básica de Dados: Experimentos | R para Estudantes de Marketing" />
  
  
  

<meta name="author" content="KU Leuven Marketing department (tradução: Rodrigo Hermont Ozon)" />


<meta name="date" content="2020-09-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="regressão-logística-opcional.html"/>
<link rel="next" href="análise-de-componentes-principais-para-mapas-perceptivos-office-dataset.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R para Estudantes de Marketing</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Sobre o autor desta tradução</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#resumo"><i class="fa fa-check"></i>Resumo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="sobre-este-tutorial.html"><a href="sobre-este-tutorial.html"><i class="fa fa-check"></i>Sobre este tutorial</a><ul>
<li class="chapter" data-level="" data-path="sobre-este-tutorial.html"><a href="sobre-este-tutorial.html#download-e-instalação-do-r-e-do-rstudio"><i class="fa fa-check"></i>Download e instalação do R e do RStudio</a></li>
<li class="chapter" data-level="" data-path="sobre-este-tutorial.html"><a href="sobre-este-tutorial.html#obtendo-familiaridade-com-o-studio"><i class="fa fa-check"></i>Obtendo familiaridade com o Studio</a><ul>
<li class="chapter" data-level="" data-path="sobre-este-tutorial.html"><a href="sobre-este-tutorial.html#console-vs.-script"><i class="fa fa-check"></i>Console vs. script</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="sobre-este-tutorial.html"><a href="sobre-este-tutorial.html#comentários"><i class="fa fa-check"></i>Comentários</a></li>
<li class="chapter" data-level="" data-path="sobre-este-tutorial.html"><a href="sobre-este-tutorial.html#pacotes"><i class="fa fa-check"></i>Pacotes</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html"><i class="fa fa-check"></i>Introdução ao R</a><ul>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#importando-dados"><i class="fa fa-check"></i>Importando dados</a></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#importando-arquivos-.csv"><i class="fa fa-check"></i>Importando arquivos .csv</a></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#ajustando-seu-diretório-de-trabalho"><i class="fa fa-check"></i>Ajustando seu diretório de trabalho</a></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#atribuindo-dados-a-objetos"><i class="fa fa-check"></i>Atribuindo dados a objetos</a></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#importando-arquivos-do-excel"><i class="fa fa-check"></i>Importando arquivos do Excel</a></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#lendo-os-dados-do-airbnb"><i class="fa fa-check"></i>Lendo os dados do Airbnb</a></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#manipulando-dataframes"><i class="fa fa-check"></i>Manipulando dataframes</a><ul>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#transformando-variáveis"><i class="fa fa-check"></i>Transformando variáveis</a></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#transformações-numéricas"><i class="fa fa-check"></i>Transformações numéricas</a></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#transformando-variáveis-com-a-função-mutate"><i class="fa fa-check"></i>Transformando variáveis com a função mutate</a></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#incluindo-ou-excluindo-e-renomeando-variáveis-colunas"><i class="fa fa-check"></i>Incluindo ou excluindo e renomeando variáveis (colunas)</a></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#incluindo-ou-excluindo-observações-linhas"><i class="fa fa-check"></i>Incluindo ou excluindo observações (linhas)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#o-operador-pipe"><i class="fa fa-check"></i>O operador pipe</a><ul>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#uma-maneira-de-escrever-o-código"><i class="fa fa-check"></i>Uma maneira de escrever o código</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#agrupando-e-resumindo"><i class="fa fa-check"></i>Agrupando e resumindo</a><ul>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#tabelas-de-frequência"><i class="fa fa-check"></i>Tabelas de frequência</a></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#estatísticas-descritivas"><i class="fa fa-check"></i>Estatísticas Descritivas</a></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#exportando-summaries-dos-dados"><i class="fa fa-check"></i>Exportando (summaries) dos dados</a></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#gráficos"><i class="fa fa-check"></i>Gráficos</a></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#diagrama-de-dispersão-scatterplot"><i class="fa fa-check"></i>Diagrama de dispersão (scatterplot)</a></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#jitter"><i class="fa fa-check"></i>Jitter</a></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#histograma"><i class="fa fa-check"></i>Histograma</a></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#transformação-logarítmica"><i class="fa fa-check"></i>Transformação logarítmica</a></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#plotando-a-mediana"><i class="fa fa-check"></i>Plotando a mediana</a></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#plotando-a-média"><i class="fa fa-check"></i>Plotando a média</a></li>
<li class="chapter" data-level="" data-path="introdução-ao-r.html"><a href="introdução-ao-r.html#salvando-imagens"><i class="fa fa-check"></i>Salvando imagens</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-analisando-dados-secundários.html"><a href="análise-básica-de-dados-analisando-dados-secundários.html"><i class="fa fa-check"></i>Análise básica de dados: analisando dados secundários</a><ul>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-analisando-dados-secundários.html"><a href="análise-básica-de-dados-analisando-dados-secundários.html#dados"><i class="fa fa-check"></i>Dados</a><ul>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-analisando-dados-secundários.html"><a href="análise-básica-de-dados-analisando-dados-secundários.html#importação"><i class="fa fa-check"></i>Importação</a></li>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-analisando-dados-secundários.html"><a href="análise-básica-de-dados-analisando-dados-secundários.html#manipulação"><i class="fa fa-check"></i>Manipulação</a></li>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-analisando-dados-secundários.html"><a href="análise-básica-de-dados-analisando-dados-secundários.html#mesclando-datasets"><i class="fa fa-check"></i>Mesclando datasets</a></li>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-analisando-dados-secundários.html"><a href="análise-básica-de-dados-analisando-dados-secundários.html#recapitulando-importação-e-manipulação"><i class="fa fa-check"></i>Recapitulando: importação e manipulação</a></li>
<li><a href="análise-básica-de-dados-analisando-dados-secundários.html#amostras-independentes-teste-t">Amostras independentes: teste <span class="math inline">\(t\)</span></a></li>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-analisando-dados-secundários.html"><a href="análise-básica-de-dados-analisando-dados-secundários.html#anova-univariada"><i class="fa fa-check"></i>ANOVA univariada</a></li>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-analisando-dados-secundários.html"><a href="análise-básica-de-dados-analisando-dados-secundários.html#suposição-de-normalidade-de-resíduos"><i class="fa fa-check"></i>Suposição de normalidade de resíduos</a></li>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-analisando-dados-secundários.html"><a href="análise-básica-de-dados-analisando-dados-secundários.html#suposição-homogeneidade-de-variâncias"><i class="fa fa-check"></i>Suposição: homogeneidade de variâncias</a></li>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-analisando-dados-secundários.html"><a href="análise-básica-de-dados-analisando-dados-secundários.html#anova"><i class="fa fa-check"></i>ANOVA</a></li>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-analisando-dados-secundários.html"><a href="análise-básica-de-dados-analisando-dados-secundários.html#teste-de-tuckey-de-diferença-significativa-verdadeira"><i class="fa fa-check"></i>Teste de Tuckey de diferença significativa verdadeira</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="regressão-linear.html"><a href="regressão-linear.html"><i class="fa fa-check"></i>Regressão Linear</a><ul>
<li class="chapter" data-level="" data-path="regressão-linear.html"><a href="regressão-linear.html#regressão-linear-simples"><i class="fa fa-check"></i>Regressão Linear Simples</a></li>
<li class="chapter" data-level="" data-path="regressão-linear.html"><a href="regressão-linear.html#correlação"><i class="fa fa-check"></i>Correlação</a></li>
<li class="chapter" data-level="" data-path="regressão-linear.html"><a href="regressão-linear.html#regressão-linear-múltipla-com-interação"><i class="fa fa-check"></i>Regressão linear múltipla, com interação</a></li>
<li class="chapter" data-level="" data-path="regressão-linear.html"><a href="regressão-linear.html#premissas"><i class="fa fa-check"></i>Premissas</a></li>
<li class="chapter" data-level="" data-path="regressão-linear.html"><a href="regressão-linear.html#normalidade-de-resíduos"><i class="fa fa-check"></i>Normalidade de resíduos</a></li>
<li class="chapter" data-level="" data-path="regressão-linear.html"><a href="regressão-linear.html#homocedasticidade-de-resíduos"><i class="fa fa-check"></i>Homocedasticidade de resíduos</a></li>
<li class="chapter" data-level="" data-path="regressão-linear.html"><a href="regressão-linear.html#multicolinearidade"><i class="fa fa-check"></i>Multicolinearidade</a></li>
<li><a href="regressão-linear.html#teste-chi2">Teste <span class="math inline">\(\chi^{2}\)</span></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="regressão-logística-opcional.html"><a href="regressão-logística-opcional.html"><i class="fa fa-check"></i>Regressão Logística (opcional)</a><ul>
<li class="chapter" data-level="" data-path="regressão-logística-opcional.html"><a href="regressão-logística-opcional.html#medindo-o-ajuste-de-uma-regressão-logística-porcentagem-classificada-corretamente"><i class="fa fa-check"></i>Medindo o ajuste de uma regressão logística: porcentagem classificada corretamente</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-experimentos.html"><a href="análise-básica-de-dados-experimentos.html"><i class="fa fa-check"></i>Análise Básica de Dados: Experimentos</a><ul>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-analisando-dados-secundários.html"><a href="análise-básica-de-dados-analisando-dados-secundários.html#dados"><i class="fa fa-check"></i>Dados</a><ul>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-analisando-dados-secundários.html"><a href="análise-básica-de-dados-analisando-dados-secundários.html#importação"><i class="fa fa-check"></i>Importação</a></li>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-analisando-dados-secundários.html"><a href="análise-básica-de-dados-analisando-dados-secundários.html#manipulação"><i class="fa fa-check"></i>Manipulação</a></li>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-experimentos.html"><a href="análise-básica-de-dados-experimentos.html#fatorar-algumas-variáveis"><i class="fa fa-check"></i>Fatorar algumas variáveis</a></li>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-experimentos.html"><a href="análise-básica-de-dados-experimentos.html#calcular-a-consistência-interna-e-a-média-de-perguntas-que-medem-o-mesmo-conceito"><i class="fa fa-check"></i>Calcular a consistência interna e a média de perguntas que medem o mesmo conceito</a></li>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-experimentos.html"><a href="análise-básica-de-dados-experimentos.html#recapitulando-importando-e-manipulando"><i class="fa fa-check"></i>Recapitulando: importando e manipulando</a></li>
</ul></li>
<li><a href="análise-básica-de-dados-experimentos.html#teste-t">Teste <span class="math inline">\(t\)</span></a><ul>
<li><a href="análise-básica-de-dados-experimentos.html#teste-t-para-amostras-independentes">Teste <span class="math inline">\(t\)</span> para amostras independentes</a></li>
<li><a href="análise-básica-de-dados-experimentos.html#teste-t-para-amostras-dependentes">Teste <span class="math inline">\(t\)</span> para amostras dependentes</a></li>
<li><a href="análise-básica-de-dados-experimentos.html#teste-t-para-amostra-única">Teste <span class="math inline">\(t\)</span> para amostra única</a></li>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-experimentos.html"><a href="análise-básica-de-dados-experimentos.html#anova-bivariada"><i class="fa fa-check"></i>ANOVA Bivariada</a></li>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-experimentos.html"><a href="análise-básica-de-dados-experimentos.html#seguindo-com-contrastes"><i class="fa fa-check"></i>Seguindo com contrastes</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-experimentos.html"><a href="análise-básica-de-dados-experimentos.html#análise-de-moderação-interação-entre-variáveis-independentes-contínuas-e-categóricas"><i class="fa fa-check"></i>Análise de moderação: interação entre variáveis independentes contínuas e categóricas</a><ul>
<li><a href="análise-básica-de-dados-experimentos.html#análise-spotlight">Análise <em>spotlight</em></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-experimentos.html"><a href="análise-básica-de-dados-experimentos.html#análise-ancova"><i class="fa fa-check"></i>Análise ANCOVA</a></li>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-experimentos.html"><a href="análise-básica-de-dados-experimentos.html#medidas-repetidas-anova"><i class="fa fa-check"></i>Medidas repetidas ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="análise-de-componentes-principais-para-mapas-perceptivos-office-dataset.html"><a href="análise-de-componentes-principais-para-mapas-perceptivos-office-dataset.html"><i class="fa fa-check"></i>Análise de componentes principais para mapas perceptivos (office dataset)</a><ul>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-analisando-dados-secundários.html"><a href="análise-básica-de-dados-analisando-dados-secundários.html#dados"><i class="fa fa-check"></i>Dados</a><ul>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-analisando-dados-secundários.html"><a href="análise-básica-de-dados-analisando-dados-secundários.html#importação"><i class="fa fa-check"></i>Importação</a></li>
<li class="chapter" data-level="" data-path="análise-básica-de-dados-analisando-dados-secundários.html"><a href="análise-básica-de-dados-analisando-dados-secundários.html#manipulação"><i class="fa fa-check"></i>Manipulação</a></li>
<li class="chapter" data-level="" data-path="análise-de-componentes-principais-para-mapas-perceptivos-office-dataset.html"><a href="análise-de-componentes-principais-para-mapas-perceptivos-office-dataset.html#recapitulação-importação-e-manipulação"><i class="fa fa-check"></i>Recapitulação: importação e manipulação</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="análise-de-componentes-principais-para-mapas-perceptivos-office-dataset.html"><a href="análise-de-componentes-principais-para-mapas-perceptivos-office-dataset.html#quantos-fatores-devemos-considerar"><i class="fa fa-check"></i>Quantos fatores devemos considerar ?</a></li>
<li class="chapter" data-level="" data-path="análise-de-componentes-principais-para-mapas-perceptivos-office-dataset.html"><a href="análise-de-componentes-principais-para-mapas-perceptivos-office-dataset.html#análise-de-componentes-principais"><i class="fa fa-check"></i>Análise de Componentes Principais</a><ul>
<li class="chapter" data-level="" data-path="análise-de-componentes-principais-para-mapas-perceptivos-office-dataset.html"><a href="análise-de-componentes-principais-para-mapas-perceptivos-office-dataset.html#cargas-fatoriais"><i class="fa fa-check"></i>Cargas fatoriais</a></li>
<li class="chapter" data-level="" data-path="análise-de-componentes-principais-para-mapas-perceptivos-office-dataset.html"><a href="análise-de-componentes-principais-para-mapas-perceptivos-office-dataset.html#plotando-as-cargas-fatoriais"><i class="fa fa-check"></i>Plotando as cargas fatoriais</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R para Estudantes de Marketing</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="análise-básica-de-dados-experimentos" class="section level1 unlisted unnumbered">
<h1>Análise Básica de Dados: Experimentos</h1>
<p>Neste capítulo, analisaremos os dados de um experimento que testou se o senso de poder das pessoas afeta sua disposição de pagar (WTP) por produtos relacionados ao status (ou seja, por consumo conspícuo) e se essa relação é diferente quando a WTP desses produtos é visível para os outros versus não.</p>
<p>Os participantes vieram ao nosso laboratório em grupos de oito ou sete. Estavam sentados em frente a um computador em cubículos semi-fechados. Na introdução, os participantes leram que primeiro teriam que preencher um questionário de personalidade e uma pesquisa sobre como eles lidavam com dinheiro. Depois disso, eles teriam que trabalhar juntos em grupos de dois em alguns quebra-cabeças.</p>
<p>A primeira parte da sessão foi um questionário de personalidade avaliando dominância e aspirações de status (Cassidy &amp; Lynn, 1989; Mead &amp; Maner, 2012). Os participantes leram 18 declarações e indicaram se cada uma delas se aplicava a elas ou não. Após o preenchimento deste questionário, os participantes foram lembrados de que, no final da sessão, teriam que trabalhar juntos com outro participante em alguns quebra-cabeças. Cada díade consistiria em um gerente e um trabalhador. Os participantes leram que a atribuição a esses papéis foi baseada em seus resultados no questionário de personalidade, mas, na realidade, a atribuição a papéis foi aleatória.</p>
<p>Os participantes na condição de alta potência então leram que eram mais adequados para serem gerentes, enquanto os participantes na condição de baixa potência liam que eram mais adequados para serem trabalhadores (Galinsky, Gruenfeld e Magee, 2003). As instruções deixaram claro que os gerentes teriam mais poder na tarefa de resolver quebra-cabeças do que os trabalhadores (eles poderiam decidir como um bônus em potencial de 20 euros seria dividido entre gerente e trabalhador). Antes de iniciar os quebra-cabeças, no entanto, os participantes foram convidados a participar de um estudo diferente.</p>
<p>Em um estudo ostensivamente diferente, a disposição dos participantes de gastar em produtos conspícuos e discretos foi medida. Na introdução desta parte do experimento, a presença do público foi manipulada. Na condição privada, os participantes foram informados simplesmente de que estávamos interessados em seus padrões de consumo. Eles foram questionados quanto gastariam em dez produtos que diferiam na medida em que poderiam ser usados para sinalizar o status. Os produtos conspícuos ou aprimoradores de status eram: um carro novo, uma casa, viagens, roupas e um relógio de pulso (para homens) ou jóias (para mulheres). Os produtos discretos ou com status neutro eram produtos de higiene pessoal básicos, medicamentos domésticos, despertador de quarto, utensílios de cozinha e limpeza doméstica (Griskevicius, et al., 2007). Os participantes responderam em uma escala de nove pontos, variando de 1: “Eu compraria itens muito baratos” a 9: “Eu compraria itens muito caros”.</p>
<p>Na condição pública, os participantes foram informados de que estávamos trabalhando em um site onde as pessoas pudessem se encontrar. Este site nos ajudaria a investigar como as pessoas formam impressões entre si com base nos padrões de consumo. Os participantes leram que primeiro teriam que indicar quanto gastariam em alguns produtos. Suas escolhas seriam resumidas em um perfil. Os outros participantes da sessão teriam que formar impressões sobre eles com base nesse perfil. Depois de ver um exemplo da aparência do perfil, os participantes passaram para a mesma medida de consumo da condição privada.</p>
<p>Em suma, o experimento tem um design 2 (poder: alto vs. baixo) x 2 (público: público vs. privado) x 2 (consumo: conspícuo vs. discreto) com poder e audiência manipulados entre os sujeitos e consumo manipulado entre os sujeitos.</p>
<p>As hipóteses neste experimento foram as seguintes:</p>
<ul>
<li>Na condição de privado, esperávamos que os participantes de baixa potência tivessem uma WTP maior do que os participantes de alta potência para produtos visíveis, mas não para produtos discretos. Esse padrão de resultados replicaria os resultados de Rucker e Galinsky (2008).</li>
<li>Esperávamos que a manipulação pública versus privada reduzisse a WTP para produtos visíveis para participantes de baixa potência, mas não para participantes de alta potência.Não esperávamos um efeito da manipulação pública versus privada na WTP para produtos discretos para participantes de baixa ou alta potência.</li>
</ul>
<p>Este experimento é descrito com mais detalhes em minha tese de doutorado (Franssens, 2016)</p>
<div id="referências" class="section level4 unlisted unnumbered">
<h4>Referências</h4>
<p>Cassidy, T., &amp; Lynn, R. (1989). <em>A multifactorial approach to achievement motivation: The development of a comprehensive measure</em>. Journal of Occupational Psychology, 62(4), 301-312.</p>
<p>Franssens, S. (2016). <em>Essays in consumer behavior (Doctoral dissertation)</em>. KU Leuven, Leuven, Belgium.</p>
<p>Galinsky, A. D., Gruenfeld, D. H., &amp; Magee, J. C. (2003). <em>From Power to action.</em> Journal of Personality and Social Psychology, 85(3), 453-466. <a href="https://doi.org/10.1037/0022-3514.85.3.453" class="uri">https://doi.org/10.1037/0022-3514.85.3.453</a></p>
<p>Griskevicius, V., Tybur, J. M., Sundie, J. M., Cialdini, R. B., Miller, G. F., &amp; Kenrick, D. T. (2007). <em>Blatant benevolence and conspicuous consumption: When romantic motives elicit strategic costly signals.</em> Journal of Personality and Social Psychology, 93(1), 85-102. <a href="https://doi.org/10.1037/0022-3514.93.1.85" class="uri">https://doi.org/10.1037/0022-3514.93.1.85</a></p>
<p>Mead, N. L., &amp; Maner, J. K. (2012). <em>On keeping your enemies close: Powerful leaders seek proximity to ingroup power threats.</em> Journal of Personality and Social Psychology, 102(3), 576-591. <a href="https://doi.org/10.1037/a0025755" class="uri">https://doi.org/10.1037/a0025755</a></p>
<p>Rucker, D. D., &amp; Galinsky, A. D. (2008). <em>Desire to acquire: Powerlessness and compensatory consumption.</em> Journal of Consumer Research, 35(2), 257-267. <a href="https://doi.org/10.1086/588569" class="uri">https://doi.org/10.1086/588569</a></p>
<hr />
</div>
<div id="dados" class="section level2 unlisted unnumbered">
<h2>Dados</h2>
<div id="importação" class="section level3 unlisted unnumbered">
<h3>Importação</h3>
<p>Faça o download dos dados <a href="http://users.telenet.be/samuelfranssens/tutorial_data/power_conspicuous_consumption.xlsx">aqui</a>. Como sempre, salve os dados em um diretório (de preferência um backup automático do software de compartilhamento de arquivos) e inicie seu script carregando o tidyverse e definindo o diretório de trabalho no diretório em que você acabou de salvar seus dados:</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="análise-básica-de-dados-experimentos.html#cb214-1"></a><span class="co">#library(tidyverse)</span></span>
<span id="cb214-2"><a href="análise-básica-de-dados-experimentos.html#cb214-2"></a><span class="co">#library(readxl) # precisamos deste pacote pois nossos dados estao num arquivo Excel</span></span>
<span id="cb214-3"><a href="análise-básica-de-dados-experimentos.html#cb214-3"></a><span class="co">#setwd(&quot;c:/dropbox/work/teaching/R/&quot;) # mudando para o nosso diretorio de trabalho</span></span>
<span id="cb214-4"><a href="análise-básica-de-dados-experimentos.html#cb214-4"></a></span>
<span id="cb214-5"><a href="análise-básica-de-dados-experimentos.html#cb214-5"></a><span class="co">#powercc &lt;- read_excel(&quot;power_conspicuous_consumption.xlsx&quot;,&quot;data&quot;) # Importe o arquivo Excel. Perceba que o nome da aba do Excel eh data</span></span></code></pre></div>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="análise-básica-de-dados-experimentos.html#cb215-1"></a><span class="kw">library</span>(readxl)</span>
<span id="cb215-2"><a href="análise-básica-de-dados-experimentos.html#cb215-2"></a></span>
<span id="cb215-3"><a href="análise-básica-de-dados-experimentos.html#cb215-3"></a>url&lt;-<span class="st">&quot;http://users.telenet.be/samuelfranssens/tutorial_data/power_conspicuous_consumption.xlsx&quot;</span></span>
<span id="cb215-4"><a href="análise-básica-de-dados-experimentos.html#cb215-4"></a>powercc &lt;-<span class="st"> </span><span class="kw">tempfile</span>()</span>
<span id="cb215-5"><a href="análise-básica-de-dados-experimentos.html#cb215-5"></a><span class="kw">download.file</span>(url, powercc, <span class="dt">mode=</span><span class="st">&quot;wb&quot;</span>)</span>
<span id="cb215-6"><a href="análise-básica-de-dados-experimentos.html#cb215-6"></a>powercc&lt;-<span class="kw">read_excel</span>(<span class="dt">path =</span> powercc, <span class="dt">sheet =</span> <span class="dv">1</span>)</span>
<span id="cb215-7"><a href="análise-básica-de-dados-experimentos.html#cb215-7"></a></span>
<span id="cb215-8"><a href="análise-básica-de-dados-experimentos.html#cb215-8"></a>powercc</span></code></pre></div>
<pre><code>## # A tibble: 147 x 39
##    subject start_date          end_date            duration finished power audience
##      &lt;dbl&gt; &lt;dttm&gt;              &lt;dttm&gt;                 &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;   
##  1       1 2012-04-19 09:32:56 2012-04-19 09:49:42    1006.        1 high  public  
##  2       2 2012-04-19 09:31:26 2012-04-19 09:51:13    1187.        1 low   public  
##  3       3 2012-04-19 09:29:50 2012-04-19 09:53:10    1400.        1 low   public  
##  4       4 2012-04-19 09:26:25 2012-04-19 09:53:21    1616.        1 low   public  
##  5       5 2012-04-19 09:20:55 2012-04-19 09:54:21    2006.        1 high  public  
##  6       6 2012-04-19 09:28:02 2012-04-19 09:55:50    1668.        1 high  public  
##  7       7 2012-04-19 09:17:54 2012-04-19 09:58:49    2455.        1 low   public  
##  8       8 2012-04-19 09:22:26 2012-04-19 10:01:40    2354.        1 high  public  
##  9       9 2012-04-19 10:13:12 2012-04-19 10:31:03    1071.        1 low   public  
## 10      10 2012-04-19 10:12:55 2012-04-19 10:31:29    1114.        1 high  public  
## # ... with 137 more rows, and 32 more variables: group_size &lt;dbl&gt;, gender &lt;chr&gt;,
## #   age &lt;dbl&gt;, dominance1 &lt;dbl&gt;, dominance2 &lt;dbl&gt;, dominance3 &lt;dbl&gt;, dominance4 &lt;dbl&gt;,
## #   dominance5 &lt;dbl&gt;, dominance6 &lt;dbl&gt;, dominance7 &lt;dbl&gt;, sa1 &lt;dbl&gt;, sa2 &lt;dbl&gt;, sa3 &lt;dbl&gt;,
## #   sa4 &lt;dbl&gt;, sa5 &lt;dbl&gt;, sa6 &lt;dbl&gt;, sa7 &lt;dbl&gt;, sa8 &lt;dbl&gt;, sa9 &lt;dbl&gt;, sa10 &lt;dbl&gt;,
## #   sa11 &lt;dbl&gt;, inconspicuous1 &lt;dbl&gt;, inconspicuous2 &lt;dbl&gt;, inconspicuous3 &lt;dbl&gt;,
## #   inconspicuous4 &lt;dbl&gt;, inconspicuous5 &lt;dbl&gt;, conspicuous1 &lt;dbl&gt;, conspicuous2 &lt;dbl&gt;,
## #   conspicuous3 &lt;dbl&gt;, conspicuous4 &lt;dbl&gt;, conspicuous5 &lt;dbl&gt;, agree &lt;dbl&gt;</code></pre>
<p>Não se esqueça de salvar seu script no diretório de trabalho.</p>
</div>
<div id="manipulação" class="section level3 unlisted unnumbered">
<h3>Manipulação</h3>
<p>Temos 39 colunas ou variáveis em nossos dados:</p>
<ul>
<li>subject identifica os participantes</li>
<li>start_date e end_date indicam o início e o fim da sessão experimental.</li>
<li>duration indica a duração da sessão experimental</li>
<li>finished: os participantes concluíram todo o experimento?</li>
<li>power (alto vs. baixo) e público (privado vs. público) são as condições experimentais</li>
<li>group_size: em grupos de quantos participantes compareceram ao laboratório?</li>
<li>gender e age do participante</li>
<li>dominance1, dominance2, etc. são as perguntas que mediram a dominância. Um exemplo é “Eu acho que gostaria de ter autoridade sobre outras pessoas”. Os participantes responderam com sim (1) ou não (0).</li>
<li>sa1, sa2 etc. são as perguntas que medem as aspirações de status. Um exemplo é: “Gostaria de um trabalho importante, onde as pessoas me admirassem”. Os participantes responderam com sim (1) ou não (0).</li>
<li>inconspicuous1, inconspicuous2, etc. contêm a WTP para os produtos inconspicuous. Escala de 1: eu compraria itens muito baratos a 9: eu compraria itens muito caros.</li>
<li>conspicuous1, conspicuous2, etc. contêm a WTP para os produtos conspícuos. Escala de 1: eu compraria itens muito baratos a 9: eu compraria itens muito caros.</li>
<li>agree: uma questão exploratória que mede se as pessoas concordam que elas são mais adequadas ao papel de trabalhador ou gerente. Os participantes responderam em uma escala de 1: muito mais adequado para a função de trabalhador (gerente) a 7: muito mais adequado para a função de gerente (trabalhador). Números mais altos indicam concordância com a atribuição de função no experimento.</li>
</ul>
</div>
<div id="fatorar-algumas-variáveis" class="section level3 unlisted unnumbered">
<h3>Fatorar algumas variáveis</h3>
<p>Após a inspeção dos dados, vemos que o tipo de subject é duplo, o que significa que o subject deve ser fatorado para que seus valores não sejam tratados como números. Também fatoraremos nossas condições experimentais:</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="análise-básica-de-dados-experimentos.html#cb217-1"></a><span class="kw">library</span>(dplyr)</span>
<span id="cb217-2"><a href="análise-básica-de-dados-experimentos.html#cb217-2"></a>powercc &lt;-<span class="st"> </span>powercc <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># nos criamos o objeto powercc anteriormente </span></span>
<span id="cb217-3"><a href="análise-básica-de-dados-experimentos.html#cb217-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">subject =</span> <span class="kw">factor</span>(subject),</span>
<span id="cb217-4"><a href="análise-básica-de-dados-experimentos.html#cb217-4"></a>         <span class="dt">power =</span> <span class="kw">factor</span>(power, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&quot;low&quot;</span>,<span class="st">&quot;high&quot;</span>)), <span class="co"># note os niveis dos argumentos</span></span>
<span id="cb217-5"><a href="análise-básica-de-dados-experimentos.html#cb217-5"></a>         <span class="dt">audience =</span> <span class="kw">factor</span>(audience, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&quot;private&quot;</span>,<span class="st">&quot;public&quot;</span>))) <span class="co"># note os niveis dos argumentos</span></span></code></pre></div>
<p>Observe que fornecemos novos levels de argumento ao fatorar poder e público. Este argumento especifica a ordem dos levels de um fator. No contexto desse experimento, é mais natural falar sobre o efeito da alta versus baixa potência no consumo do que falar sobre o efeito da baixa versus alta potência no consumo. Portanto, dizemos ao R que o baixo nível de energia deve ser considerado como o primeiro nível. Mais adiante, veremos que o resultado das análises pode ser interpretado como efeitos de alta potência (segundo nível) vs. baixa potência (primeiro nível). O mesmo raciocínio se aplica ao fator público, embora não seja necessário fornecer os níveis para esse fator porque o privado vem antes do público em ordem alfabética. Sua escolha do nível para o primeiro ou nível de referência influencia apenas a interpretação, não o resultado real da análise.</p>
<p>Em uma sessão experimental, o alarme de incêndio disparou e tivemos que sair do laboratório. Vamos remover os participantes que não concluíram a experiência:</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="análise-básica-de-dados-experimentos.html#cb218-1"></a>powercc &lt;-<span class="st"> </span>powercc <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># nos ja criamos o objeto powercc anteriormente</span></span>
<span id="cb218-2"><a href="análise-básica-de-dados-experimentos.html#cb218-2"></a><span class="st">  </span><span class="kw">filter</span>(finished <span class="op">==</span><span class="st"> </span><span class="dv">1</span>) <span class="co"># somente mantenha as observacoes que sao terminadas ou iguais a 1</span></span></code></pre></div>
<p>Observe o dobro <span class="math inline">\(==\)</span> ao testar a igualdade. Confira o livro <a href="https://r4ds.had.co.nz/transform.html#filter-rows-with-filter">R4 Data Science para outros operadores lógicos (role para baixo para chegar à Seção 5.2.2).</a></p>
</div>
<div id="calcular-a-consistência-interna-e-a-média-de-perguntas-que-medem-o-mesmo-conceito" class="section level3 unlisted unnumbered">
<h3>Calcular a consistência interna e a média de perguntas que medem o mesmo conceito</h3>
<p>Gostaríamos de calcular a média das perguntas que medem a dominância para obter um único número indicando se o participante tem uma personalidade dominante ou não dominante. Antes de fazer isso, devemos ter uma idéia da consistência interna das perguntas que medem o domínio. Isso nos dirá se todas essas perguntas medem o mesmo conceito. Uma medida da consistência interna é o alfa de Cronbach. Para calcular, precisamos de um pacote chamado psych:</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="análise-básica-de-dados-experimentos.html#cb219-1"></a><span class="co">#install.packages(&quot;psych&quot;)</span></span>
<span id="cb219-2"><a href="análise-básica-de-dados-experimentos.html#cb219-2"></a><span class="kw">library</span>(psych)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;psych&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:car&#39;:
## 
##     logit</code></pre>
<pre><code>## The following object is masked from &#39;package:Hmisc&#39;:
## 
##     describe</code></pre>
<pre><code>## The following objects are masked from &#39;package:ggplot2&#39;:
## 
##     %+%, alpha</code></pre>
<p>Depois que o pacote for carregado, podemos usar a função alfa para calcular o alfa de Cronbach para um conjunto de perguntas:</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="análise-básica-de-dados-experimentos.html#cb224-1"></a>dominance.questions &lt;-<span class="st"> </span>powercc <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb224-2"><a href="análise-básica-de-dados-experimentos.html#cb224-2"></a><span class="st">  </span><span class="kw">select</span>(<span class="kw">starts_with</span>(<span class="st">&quot;dominance&quot;</span>)) <span class="co"># pegue o dataframe powercc e selecione todas as viariaveis com o nome que se inicia com dominancia</span></span>
<span id="cb224-3"><a href="análise-básica-de-dados-experimentos.html#cb224-3"></a></span>
<span id="cb224-4"><a href="análise-básica-de-dados-experimentos.html#cb224-4"></a><span class="kw">alpha</span>(dominance.questions) <span class="co"># calcula o alfa de cronbach para essas variaveis</span></span></code></pre></div>
<pre><code>## 
## Reliability analysis   
## Call: alpha(x = dominance.questions)
## 
##   raw_alpha std.alpha G6(smc) average_r S/N   ase mean   sd median_r
##       0.69      0.67    0.67      0.23 2.1 0.038 0.63 0.27     0.21
## 
##  lower alpha upper     95% confidence boundaries
## 0.61 0.69 0.76 
## 
##  Reliability if an item is dropped:
##            raw_alpha std.alpha G6(smc) average_r S/N alpha se var.r med.r
## dominance1      0.68      0.67    0.66      0.25 2.0    0.039 0.016  0.22
## dominance2      0.65      0.63    0.62      0.22 1.7    0.043 0.018  0.21
## dominance3      0.59      0.58    0.56      0.19 1.4    0.050 0.014  0.20
## dominance4      0.62      0.60    0.59      0.20 1.5    0.047 0.018  0.21
## dominance5      0.65      0.64    0.63      0.23 1.7    0.043 0.021  0.21
## dominance6      0.70      0.70    0.68      0.28 2.4    0.038 0.009  0.25
## dominance7      0.65      0.64    0.62      0.23 1.8    0.043 0.017  0.20
## 
##  Item statistics 
##              n raw.r std.r r.cor r.drop mean   sd
## dominance1 143  0.52  0.49  0.33   0.29 0.53 0.50
## dominance2 143  0.59  0.61  0.52   0.42 0.80 0.40
## dominance3 143  0.75  0.74  0.71   0.59 0.52 0.50
## dominance4 143  0.68  0.68  0.61   0.50 0.58 0.50
## dominance5 143  0.61  0.59  0.48   0.40 0.55 0.50
## dominance6 143  0.29  0.38  0.19   0.14 0.91 0.29
## dominance7 143  0.62  0.59  0.48   0.41 0.53 0.50
## 
## Non missing response frequency for each item
##               0    1 miss
## dominance1 0.47 0.53    0
## dominance2 0.20 0.80    0
## dominance3 0.48 0.52    0
## dominance4 0.42 0.58    0
## dominance5 0.45 0.55    0
## dominance6 0.09 0.91    0
## dominance7 0.47 0.53    0</code></pre>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="análise-básica-de-dados-experimentos.html#cb226-1"></a><span class="co"># Observe que também poderíamos ter escrito isso da seguinte maneira:</span></span>
<span id="cb226-2"><a href="análise-básica-de-dados-experimentos.html#cb226-2"></a><span class="co"># powercc %&gt;% select(starts_with(&quot;dominance&quot;)) %&gt;% cronbach()</span></span></code></pre></div>
<p>Isso produz muita saída. Em raw_alpha, vemos que o alfa é 0,69, que fica no lado inferior (0,70 é geralmente considerado o mínimo necessário), mas ainda está ok. A tabela abaixo nos diz qual seria o alfa se retirássemos uma pergunta de nossa medida. A queda da dominance6 aumentaria o alfa para 0,7. Comparado ao alfa original de 0,69, esse aumento é pequeno e, portanto, não perdemos a dominance6. Se houvesse uma pergunta com um alto “alfa se descartado”, isso indicaria que esta pergunta está medindo algo diferente das outras perguntas. Nesse caso, você pode considerar remover esta pergunta da sua medida.</p>
<p>Podemos proceder calculando a média das respostas sobre a questão do domínio:</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="análise-básica-de-dados-experimentos.html#cb227-1"></a>powercc &lt;-<span class="st"> </span>powercc <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb227-2"><a href="análise-básica-de-dados-experimentos.html#cb227-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">dominance =</span> (dominance1<span class="op">+</span>dominance2<span class="op">+</span>dominance3<span class="op">+</span>dominance4<span class="op">+</span>dominance5<span class="op">+</span>dominance6<span class="op">+</span>dominance7)<span class="op">/</span><span class="dv">7</span>,</span>
<span id="cb227-3"><a href="análise-básica-de-dados-experimentos.html#cb227-3"></a>         <span class="dt">cc =</span> (conspicuous1<span class="op">+</span>conspicuous2<span class="op">+</span>conspicuous3<span class="op">+</span>conspicuous4<span class="op">+</span>conspicuous5)<span class="op">/</span><span class="dv">5</span>,</span>
<span id="cb227-4"><a href="análise-básica-de-dados-experimentos.html#cb227-4"></a>         <span class="dt">icc =</span> (inconspicuous1<span class="op">+</span>inconspicuous2<span class="op">+</span>inconspicuous3<span class="op">+</span>inconspicuous4<span class="op">+</span>inconspicuous5)<span class="op">/</span><span class="dv">5</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb227-5"><a href="análise-básica-de-dados-experimentos.html#cb227-5"></a><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span><span class="kw">starts_with</span>(<span class="st">&quot;sa&quot;</span>))</span></code></pre></div>
<p>Também calculei a média das perguntas sobre consumo conspícuo e consumo discreto, mas não sobre as aspirações de status porque o alfa de Cronbach era muito baixo. Excluí as perguntas sobre aspirações de status do conjunto de dados. Deixo como um exercício verificar os alfa de Cronbach de cada um desses conceitos (faça isso antes de excluir as perguntas sobre as aspirações de status, é claro).</p>
</div>
<div id="recapitulando-importando-e-manipulando" class="section level3 unlisted unnumbered">
<h3>Recapitulando: importando e manipulando</h3>
<p>Aqui está o que fizemos até agora, em uma sequência ordenada de operações canalizadas (faça o <a href="http://users.telenet.be/samuelfranssens/tutorial_data/power_conspicuous_consumption.xlsx">download</a> dos dados aqui}):</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="análise-básica-de-dados-experimentos.html#cb228-1"></a><span class="co">#library(tidyverse)</span></span>
<span id="cb228-2"><a href="análise-básica-de-dados-experimentos.html#cb228-2"></a><span class="co">#library(readxl)</span></span>
<span id="cb228-3"><a href="análise-básica-de-dados-experimentos.html#cb228-3"></a><span class="co">#setwd(&quot;c:/dropbox/work/teaching/R/&quot;) # mudando para seu proprio diretorio</span></span>
<span id="cb228-4"><a href="análise-básica-de-dados-experimentos.html#cb228-4"></a></span>
<span id="cb228-5"><a href="análise-básica-de-dados-experimentos.html#cb228-5"></a><span class="co">#powercc &lt;- read_excel(&quot;power_conspicuous_consumption.xlsx&quot;,&quot;data&quot;)  %&gt;%</span></span>
<span id="cb228-6"><a href="análise-básica-de-dados-experimentos.html#cb228-6"></a> <span class="co"># filter(finished == 1) %&gt;% </span></span>
<span id="cb228-7"><a href="análise-básica-de-dados-experimentos.html#cb228-7"></a>  <span class="co">#mutate(subject = factor(subject),</span></span>
<span id="cb228-8"><a href="análise-básica-de-dados-experimentos.html#cb228-8"></a>   <span class="co">#      power = factor(power, levels = c(&quot;low&quot;,&quot;high&quot;)),</span></span>
<span id="cb228-9"><a href="análise-básica-de-dados-experimentos.html#cb228-9"></a></span>
<span id="cb228-10"><a href="análise-básica-de-dados-experimentos.html#cb228-10"></a>    <span class="co">#     audience = factor(audience, levels = c(&quot;private&quot;,&quot;public&quot;)),</span></span>
<span id="cb228-11"><a href="análise-básica-de-dados-experimentos.html#cb228-11"></a>     <span class="co">#    dominance = (dominance1+dominance2+dominance3+dominance4+dominance5+dominance6+dominance7)/7,</span></span>
<span id="cb228-12"><a href="análise-básica-de-dados-experimentos.html#cb228-12"></a>     <span class="co">#    cc = (conspicuous1+conspicuous2+conspicuous3+conspicuous4+conspicuous5)/5,</span></span>
<span id="cb228-13"><a href="análise-básica-de-dados-experimentos.html#cb228-13"></a>      <span class="co">#   icc = (inconspicuous1+inconspicuous2+inconspicuous3+inconspicuous4+inconspicuous5)/5) %&gt;% </span></span>
<span id="cb228-14"><a href="análise-básica-de-dados-experimentos.html#cb228-14"></a>  <span class="co"># select(-starts_with(&quot;sa&quot;))</span></span></code></pre></div>
</div>
</div>
<div id="teste-t" class="section level2 unlisted unnumbered">
<h2>Teste <span class="math inline">\(t\)</span></h2>
<div id="teste-t-para-amostras-independentes" class="section level3 unlisted unnumbered">
<h3>Teste <span class="math inline">\(t\)</span> para amostras independentes</h3>
<p>Digamos que queremos testar se homens e mulheres diferem no grau em que são dominantes. Vamos criar um boxplot primeiro e depois verificar as médias e os desvios padrão:</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="análise-básica-de-dados-experimentos.html#cb229-1"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb229-2"><a href="análise-básica-de-dados-experimentos.html#cb229-2"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> powercc, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> gender, <span class="dt">y =</span> dominance)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb229-3"><a href="análise-básica-de-dados-experimentos.html#cb229-3"></a><span class="st">  </span><span class="kw">geom_boxplot</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-110-1.png" width="672" /></p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="análise-básica-de-dados-experimentos.html#cb230-1"></a>powercc <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb230-2"><a href="análise-básica-de-dados-experimentos.html#cb230-2"></a><span class="st">  </span><span class="kw">group_by</span>(gender) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb230-3"><a href="análise-básica-de-dados-experimentos.html#cb230-3"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean_dominance =</span> <span class="kw">mean</span>(dominance),</span>
<span id="cb230-4"><a href="análise-básica-de-dados-experimentos.html#cb230-4"></a>            <span class="dt">sd_dominance =</span> <span class="kw">sd</span>(dominance))</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 2 x 3
##   gender mean_dominance sd_dominance
##   &lt;chr&gt;           &lt;dbl&gt;        &lt;dbl&gt;
## 1 female          0.614        0.247
## 2 male            0.646        0.296</code></pre>
<p>Os homens pontuam um pouco mais alto que as mulheres, mas queremos saber se essa diferença é significativa. Um teste <span class="math inline">\(t\)</span> de amostras independentes pode fornecer a resposta (os homens e as mulheres em nosso experimento são amostras independentes), mas precisamos verificar primeiro uma suposição: as variações das duas amostras independentes são iguais?</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="análise-básica-de-dados-experimentos.html#cb233-1"></a><span class="co">#install.packages(&quot;car&quot;) # para o teste de variancias iguais, precisamos de um pacote chamado car</span></span>
<span id="cb233-2"><a href="análise-básica-de-dados-experimentos.html#cb233-2"></a><span class="kw">library</span>(car)</span>
<span id="cb233-3"><a href="análise-básica-de-dados-experimentos.html#cb233-3"></a></span>
<span id="cb233-4"><a href="análise-básica-de-dados-experimentos.html#cb233-4"></a><span class="co"># Teste Levene para igualdade de variancias.</span></span>
<span id="cb233-5"><a href="análise-básica-de-dados-experimentos.html#cb233-5"></a><span class="co"># Baixo valor-p indica que as variancias nao sejam iguais.</span></span>
<span id="cb233-6"><a href="análise-básica-de-dados-experimentos.html#cb233-6"></a><span class="co"># Primeiro argumento = variavel dependente continua, segundo argumento = variavel independente categorica</span></span>
<span id="cb233-7"><a href="análise-básica-de-dados-experimentos.html#cb233-7"></a></span>
<span id="cb233-8"><a href="análise-básica-de-dados-experimentos.html#cb233-8"></a><span class="kw">leveneTest</span>(powercc<span class="op">$</span>dominance, powercc<span class="op">$</span>gender) </span></code></pre></div>
<pre><code>## Warning in leveneTest.default(powercc$dominance, powercc$gender): powercc$gender coerced to
## factor.</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##        Df F value Pr(&gt;F)
## group   1  2.1915  0.141
##       141</code></pre>
<p>A hipótese nula de variâncias iguais não é rejeitada (<span class="math inline">\(p = 0,14\)</span>), para que possamos continuar com um teste <span class="math inline">\(t\)</span> que assume variâncias iguais:</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="análise-básica-de-dados-experimentos.html#cb236-1"></a><span class="co"># Teste se os meios de dominancia diferem entre os sexos.</span></span>
<span id="cb236-2"><a href="análise-básica-de-dados-experimentos.html#cb236-2"></a><span class="co"># Indique se o teste deve assumir variacoes iguais ou nao (define var.equal = FALSE para um teste que nao assume variacoes iguais).</span></span>
<span id="cb236-3"><a href="análise-básica-de-dados-experimentos.html#cb236-3"></a></span>
<span id="cb236-4"><a href="análise-básica-de-dados-experimentos.html#cb236-4"></a><span class="kw">t.test</span>(powercc<span class="op">$</span>dominance <span class="op">~</span><span class="st"> </span>powercc<span class="op">$</span>gender, <span class="dt">var.equal =</span> <span class="ot">TRUE</span>) </span></code></pre></div>
<pre><code>## 
## 	Two Sample t-test
## 
## data:  powercc$dominance by powercc$gender
## t = -0.6899, df = 141, p-value = 0.4914
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.12179092  0.05877722
## sample estimates:
## mean in group female   mean in group male 
##            0.6142857            0.6457926</code></pre>
<p>Você pode relatar o seguinte: “Homens (<span class="math inline">\(M = 0,65, DP = 0,3\)</span>) e mulheres (<span class="math inline">\(M = 0,61, DP = 0,25\)</span>) não diferiram no grau em que se classificaram como dominantes (<span class="math inline">\(t (141) = -0,69 , p = 0,49\)</span>).”</p>
</div>
<div id="teste-t-para-amostras-dependentes" class="section level3 unlisted unnumbered">
<h3>Teste <span class="math inline">\(t\)</span> para amostras dependentes</h3>
<p>Digamos que queremos testar se as pessoas estão mais dispostas a gastar em itens conspícuos do que em itens discretos. Vamos verificar os meios e os desvios padrão primeiro:</p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="análise-básica-de-dados-experimentos.html#cb238-1"></a>powercc <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># nao ha necessidade de agrupar! nao estamos dividindo nossa amostra em subgrupos</span></span>
<span id="cb238-2"><a href="análise-básica-de-dados-experimentos.html#cb238-2"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean_cc =</span> <span class="kw">mean</span>(cc), <span class="dt">sd_cc =</span> <span class="kw">sd</span>(cc),</span>
<span id="cb238-3"><a href="análise-básica-de-dados-experimentos.html#cb238-3"></a>            <span class="dt">mean_icc =</span> <span class="kw">mean</span>(icc), <span class="dt">sd_icc =</span> <span class="kw">sd</span>(icc))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   mean_cc sd_cc mean_icc sd_icc
##     &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;
## 1    6.01  1.05     3.60  0.988</code></pre>
<p>As médias são mais altas para produtos conspícuos do que para produtos discretos, mas queremos saber se essa diferença é significativa e, portanto, realizar um teste t de amostras dependentes (cada participante classifica produtos conspícuos e discretos, portanto, essas classificações são dependentes):</p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb240-1"><a href="análise-básica-de-dados-experimentos.html#cb240-1"></a><span class="kw">t.test</span>(powercc<span class="op">$</span>cc, powercc<span class="op">$</span>icc, <span class="dt">paired =</span> <span class="ot">TRUE</span>) <span class="co"># Teste se as medias de cc e icc sao diferentes. Indique que este eh um teste t de amostras dependentes com emparelhado = TRUE.</span></span></code></pre></div>
<pre><code>## 
## 	Paired t-test
## 
## data:  powercc$cc and powercc$icc
## t = 25.064, df = 142, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  2.214575 2.593816
## sample estimates:
## mean of the differences 
##                2.404196</code></pre>
<p>Você pode relatar o seguinte: “As pessoas indicaram que estavam dispostas a pagar mais (<span class="math inline">\(t (142) = 25.064\)</span>, <span class="math inline">\(p &lt;0,001\)</span>) por produtos conspícuos (<span class="math inline">\(M = 6,01, DP = 1,05\)</span>) do que por produtos discretos (<span class="math inline">\(M = 3,6, DP = 0,99\)</span>).”</p>
</div>
<div id="teste-t-para-amostra-única" class="section level3 unlisted unnumbered">
<h3>Teste <span class="math inline">\(t\)</span> para amostra única</h3>
<p>Digamos que queremos testar se a disposição média de pagar pelos itens visíveis foi significativamente maior que 5 (o ponto médio da escala):</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="análise-básica-de-dados-experimentos.html#cb242-1"></a><span class="kw">t.test</span>(powercc<span class="op">$</span>cc, <span class="dt">mu =</span> <span class="dv">5</span>) <span class="co"># Indique a variavel cuja media queremos comparar com um valor especifico (5).</span></span></code></pre></div>
<pre><code>## 
## 	One Sample t-test
## 
## data:  powercc$cc
## t = 11.499, df = 142, p-value &lt; 2.2e-16
## alternative hypothesis: true mean is not equal to 5
## 95 percent confidence interval:
##  5.833886 6.180100
## sample estimates:
## mean of x 
##  6.006993</code></pre>
<p>Na verdade, é significativamente maior que 5. Você pode relatar o seguinte: “A WTP média para produtos conspícuos (M = 6,01, DP = 1,05) estava significativamente acima de 5 (t (142) = 11,499, <span class="math inline">\(p &lt;0,001\)</span>).”</p>
</div>
<div id="anova-bivariada" class="section level3 unlisted unnumbered">
<h3>ANOVA Bivariada</h3>
<p>Quando você lê um artigo acadêmico que relata um experimento, a seção de resultados geralmente começa com uma discussão dos principais efeitos dos fatores experimentais e sua interação, conforme testado por uma Análise de variância ou ANOVA. Vamos nos concentrar primeiro na WTP para produtos que melhoram o status. (Consideramos brevemente a WTP para produtos com status neutro em nossa discussão sobre testes t de amostras dependentes e discutiremos mais detalhadamente na seção ANOVA de medidas repetidas.)</p>
<p>Vamos inspecionar algumas estatísticas descritivas primeiro. Gostaríamos de ver a WTP média para produtos visíveis, o desvio padrão dessa WTP e o número de participantes em cada célula experimental. Já aprendemos como fazer isso no capítulo introdutório (consulte as tabelas de frequência e as estatísticas descritivas):</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="análise-básica-de-dados-experimentos.html#cb244-1"></a>powercc.summary &lt;-<span class="st"> </span>powercc <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># estamos atribuindo o resumo a um objeto, porque precisaremos desse resumo para fazer um grafico de barras</span></span>
<span id="cb244-2"><a href="análise-básica-de-dados-experimentos.html#cb244-2"></a><span class="st">  </span><span class="kw">group_by</span>(audience, power) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># agora agrupamos por duas variaveis</span></span>
<span id="cb244-3"><a href="análise-básica-de-dados-experimentos.html#cb244-3"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">count =</span> <span class="kw">n</span>(),</span>
<span id="cb244-4"><a href="análise-básica-de-dados-experimentos.html#cb244-4"></a>            <span class="dt">mean =</span> <span class="kw">mean</span>(cc),</span>
<span id="cb244-5"><a href="análise-básica-de-dados-experimentos.html#cb244-5"></a>            <span class="dt">sd =</span> <span class="kw">sd</span>(cc))</span></code></pre></div>
<pre><code>## `summarise()` regrouping output by &#39;audience&#39; (override with `.groups` argument)</code></pre>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="análise-básica-de-dados-experimentos.html#cb246-1"></a>powercc.summary</span></code></pre></div>
<pre><code>## # A tibble: 4 x 5
## # Groups:   audience [2]
##   audience power count  mean    sd
##   &lt;fct&gt;    &lt;fct&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 private  low      34  6.08 1.04 
## 2 private  high     31  5.63 0.893
## 3 public   low      40  6.17 1.15 
## 4 public   high     38  6.07 1.03</code></pre>
<p>Vemos que a diferença na WTP entre os participantes de alta e baixa potência é maior na condição privada do que na pública.</p>
<p>Vamos resumir esses resultados em um gráfico de caixa:</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="análise-básica-de-dados-experimentos.html#cb248-1"></a><span class="co"># ao criar um grafico de caixa, o conjunto de dados que serve como entrada para o ggplot eh o conjunto de dados completo, nao o resumo com os meios</span></span>
<span id="cb248-2"><a href="análise-básica-de-dados-experimentos.html#cb248-2"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> powercc, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> audience, <span class="dt">y =</span> cc, <span class="dt">fill =</span> power)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb248-3"><a href="análise-básica-de-dados-experimentos.html#cb248-3"></a><span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="co"># argumentos sao os mesmos que para geom_bar, mas agora fornecemos a geom_boxplot</span></span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-118-1.png" width="672" /></p>
<p>Os gráficos boxplot são informativos porque nos dão uma idéia da mediana e da distribuição dos dados. No entanto, em trabalhos acadêmicos, os resultados das experiências são tradicionalmente resumidos em gráficos de barras (mesmo que os gráficos boxplots sejam mais informativos).</p>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="análise-básica-de-dados-experimentos.html#cb249-1"></a><span class="co"># ao criar um grafico de barras, o conjunto de dados que serve como entrada para o ggplot eh o resumo com os meios, nao o conjunto de dados completo</span></span>
<span id="cb249-2"><a href="análise-básica-de-dados-experimentos.html#cb249-2"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> powercc.summary, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> audience, <span class="dt">y =</span> mean, <span class="dt">fill =</span> power)) <span class="op">+</span></span>
<span id="cb249-3"><a href="análise-básica-de-dados-experimentos.html#cb249-3"></a><span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="dt">position =</span> <span class="st">&quot;dodge&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-119-1.png" width="672" /></p>
<p>Para criar um gráfico de barras, informamos ao ggplot as variáveis que devem estar no eixo X e no eixo Y e também usamos cores diferentes para diferentes níveis de potência com o comando fill. Então pedimos um gráfico de barras com geom_bar. stat = “identity” e position = “dodge” devem ser incluídos como argumentos para geom_bar, mas uma discussão sobre esses argumentos está além do escopo deste tutorial.</p>
<p>Antes de prosseguirmos com a ANOVA, devemos verificar se suas premissas são atendidas. Discutimos as suposições da ANOVA anteriormente, mas ignoramos aqui.</p>
<p>Para realizar uma ANOVA, precisamos instalar alguns pacotes:</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="análise-básica-de-dados-experimentos.html#cb250-1"></a><span class="co">#install.packages(remotes) # O pacote de controles remotos nos permite instalar pacotes armazenados no GitHub, um site para desenvolvedores de pacotes.</span></span>
<span id="cb250-2"><a href="análise-básica-de-dados-experimentos.html#cb250-2"></a><span class="co">#install.packages(&quot;car&quot;) # Tambem precisaremos do pacote do carro para executar a ANOVA (não é necessário reinstala-lo se você já tiver feito isso).</span></span>
<span id="cb250-3"><a href="análise-básica-de-dados-experimentos.html#cb250-3"></a></span>
<span id="cb250-4"><a href="análise-básica-de-dados-experimentos.html#cb250-4"></a><span class="kw">library</span>(remotes)</span>
<span id="cb250-5"><a href="análise-básica-de-dados-experimentos.html#cb250-5"></a><span class="kw">install_github</span>(<span class="st">&#39;samuelfranssens/type3anova&#39;</span>) <span class="co"># Instale o pacote type3anova. Esta e as etapas anteriores precisam ser executadas apenas uma vez.</span></span></code></pre></div>
<pre><code>## Skipping install of &#39;type3anova&#39; from a github remote, the SHA1 (0c38377d) has not changed since last install.
##   Use `force = TRUE` to force installation</code></pre>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="análise-básica-de-dados-experimentos.html#cb252-1"></a><span class="kw">library</span>(type3anova) <span class="co"># Carrega o pacote type3anova </span></span></code></pre></div>
<p>Agora podemos prosseguir com a ANOVA real:</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="análise-básica-de-dados-experimentos.html#cb253-1"></a><span class="co"># Cria um modelo linear primeiramente</span></span>
<span id="cb253-2"><a href="análise-básica-de-dados-experimentos.html#cb253-2"></a><span class="co"># A funcao lm() toma os dados e os argumentos</span></span>
<span id="cb253-3"><a href="análise-básica-de-dados-experimentos.html#cb253-3"></a><span class="co"># A formula tem a seguinte sintaxe: variavel dependente  ~ variavel independente</span></span>
<span id="cb253-4"><a href="análise-básica-de-dados-experimentos.html#cb253-4"></a>linearmodel &lt;-<span class="st"> </span><span class="kw">lm</span>(cc <span class="op">~</span><span class="st"> </span>power<span class="op">*</span>audience, <span class="dt">data=</span>powercc) </span>
<span id="cb253-5"><a href="análise-básica-de-dados-experimentos.html#cb253-5"></a><span class="co"># power*audience: interacao eh calculada</span></span>
<span id="cb253-6"><a href="análise-básica-de-dados-experimentos.html#cb253-6"></a><span class="co"># power+audience: interacao nao eh incluida</span></span>
<span id="cb253-7"><a href="análise-básica-de-dados-experimentos.html#cb253-7"></a></span>
<span id="cb253-8"><a href="análise-básica-de-dados-experimentos.html#cb253-8"></a><span class="kw">type3anova</span>(linearmodel) <span class="co"># Em seguida, peça a saída no formato ANOVA. Isso fornece a soma dos quadrados do Tipo III. Observe que isso é diferente da anova (modelo linear), que fornece a soma dos quadrados do tipo I.</span></span></code></pre></div>
<pre><code>## # A tibble: 5 x 6
##   term                ss   df1   df2       f pvalue
##   &lt;chr&gt;            &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;  &lt;dbl&gt;
## 1 (Intercept)    5080.       1   139 4710.    0    
## 2 power             2.64     1   139    2.45  0.12 
## 3 audience          2.48     1   139    2.30  0.132
## 4 power:audience    1.11     1   139    1.03  0.313
## 5 Residuals       150.     139   139   NA    NA</code></pre>
<p>Você pode relatar esses resultados da seguinte forma: “Nem o principal efeito do poder (F (1, 139) = 2,45, p = 0,12), nem o principal efeito do público (F (1, 139) = 2,3, p = 0,13), nem a interação entre poder e público (F (1, 139) = 1,03, p = 0,31) foi significativa.”</p>
</div>
<div id="seguindo-com-contrastes" class="section level3 unlisted unnumbered">
<h3>Seguindo com contrastes</h3>
<p>Ao realizar um experimento 2 x 2, geralmente fazemos a hipótese de uma interação. Uma interação significa que o efeito de uma variável independente é diferente dependendo dos níveis da outra variável independente. Na seção anterior, a ANOVA nos disse que a interação entre poder e público não era significativa. Isso significa que o efeito de alta versus baixa potência foi o mesmo na condição privada e pública e que o efeito de público versus privado foi o mesmo na condição de alta e baixa potência. Normalmente, a análise para com a não significância da interação. No entanto, faremos os testes de acompanhamento que um faria se a interação fosse significativa.</p>
<p>Vamos considerar o significado da célula novamente:</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="análise-básica-de-dados-experimentos.html#cb255-1"></a>powercc.summary &lt;-<span class="st"> </span>powercc <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb255-2"><a href="análise-básica-de-dados-experimentos.html#cb255-2"></a><span class="st">  </span><span class="kw">group_by</span>(audience, power) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb255-3"><a href="análise-básica-de-dados-experimentos.html#cb255-3"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">count =</span> <span class="kw">n</span>(),</span>
<span id="cb255-4"><a href="análise-básica-de-dados-experimentos.html#cb255-4"></a>            <span class="dt">mean =</span> <span class="kw">mean</span>(cc),</span>
<span id="cb255-5"><a href="análise-básica-de-dados-experimentos.html#cb255-5"></a>            <span class="dt">sd =</span> <span class="kw">sd</span>(cc))</span></code></pre></div>
<pre><code>## `summarise()` regrouping output by &#39;audience&#39; (override with `.groups` argument)</code></pre>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="análise-básica-de-dados-experimentos.html#cb257-1"></a><span class="co"># ao criar um grafico de barras, o conjunto de dados que serve como entrada para o ggplot eh o resumo com os meios, nao o conjunto de dados completo</span></span>
<span id="cb257-2"><a href="análise-básica-de-dados-experimentos.html#cb257-2"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> powercc.summary,<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> audience, <span class="dt">y =</span> mean, <span class="dt">fill =</span> power)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb257-3"><a href="análise-básica-de-dados-experimentos.html#cb257-3"></a><span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="dt">position =</span> <span class="st">&quot;dodge&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-122-1.png" width="672" /></p>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb258-1"><a href="análise-básica-de-dados-experimentos.html#cb258-1"></a>powercc.summary</span></code></pre></div>
<pre><code>## # A tibble: 4 x 5
## # Groups:   audience [2]
##   audience power count  mean    sd
##   &lt;fct&gt;    &lt;fct&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 private  low      34  6.08 1.04 
## 2 private  high     31  5.63 0.893
## 3 public   low      40  6.17 1.15 
## 4 public   high     38  6.07 1.03</code></pre>
<p>Queremos testar se a diferença entre alta e baixa potência na condição privada é significativa (baixa: 6,08 vs. alta: 5,63) e se a diferença entre alta e baixa potência na condição pública é significativa (baixa: 6,17 vs. alta : 6,07). Para fazer isso, podemos usar a função de contraste da biblioteca type3anova que instalamos anteriormente. A função de contraste usa dois argumentos: um modelo linear e uma especificação de contraste. O modelo linear é o mesmo de antes:</p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="análise-básica-de-dados-experimentos.html#cb260-1"></a>linearmodel &lt;-<span class="st"> </span><span class="kw">lm</span>(cc <span class="op">~</span><span class="st"> </span>power<span class="op">*</span>audience, <span class="dt">data=</span>powercc)</span></code></pre></div>
<p>Mas, para saber como devemos especificar nosso contraste, precisamos dar uma olhada nos coeficientes de regressão em nosso modelo linear:</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="análise-básica-de-dados-experimentos.html#cb261-1"></a><span class="kw">summary</span>(linearmodel)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = cc ~ power * audience, data = powercc)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.7700 -0.6737  0.1177  0.7177  2.3263 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)               6.08235    0.17812  34.148   &lt;2e-16 ***
## powerhigh                -0.45009    0.25792  -1.745   0.0832 .  
## audiencepublic            0.08765    0.24226   0.362   0.7181    
## powerhigh:audiencepublic  0.35378    0.34910   1.013   0.3126    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.039 on 139 degrees of freedom
## Multiple R-squared:  0.03711,	Adjusted R-squared:  0.01633 
## F-statistic: 1.786 on 3 and 139 DF,  p-value: 0.1527</code></pre>
<p>Temos 4 coeficientes de regressão:</p>
<ul>
<li><span class="math inline">\(\beta_{0}\)</span> ou intercepto</li>
<li><span class="math inline">\(\beta_{1}\)</span> ou o coeficiente de powerhigh ou o alto nível do fator de potência (-0,45)</li>
<li><span class="math inline">\(\beta_{2}\)</span> ou o coeficiente para audiencepublic ou o nível público do fator público (0,09)</li>
<li><span class="math inline">\(\beta_{3}\)</span> ou coeficiente para: powerhigh:audiencepublic (0.35)</li>
</ul>
<p>Vemos que a estimativa para a interceptação corresponde à média observada na célula privada de baixa potência. Adicione a isso a estimativa de powerhigh e obteremos a média observada na célula privada de alta potência. Adicione à estimativa para a interceptação, a estimativa de audiencepublic e obtenha a média observada na célula pública de baixa potência. Adicione à estimativa para a interceptação, a estimativa de powerhigh, audiencepublic e powerhigh:audiencepublic e obteremos a média observada na célula pública de alto poder. Geralmente visualizo isso em uma tabela (e salvo no meu script) para facilitar a especificação do contraste que quero testar:</p>
<p>Digamos que estamos contrastando energia alta versus baixa na condição privada e testamos se (<span class="math inline">\(\beta_{0}+\beta_{1}\)</span> e <span class="math inline">\(\beta_{0}\)</span> diferem significativamente ou se (<span class="math inline">\(\beta_{0}+\beta_{1})-\beta_{0}=\beta_{1}\)</span> é significativamente diferente de zero. Nós especificamos isso da seguinte maneira:</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="análise-básica-de-dados-experimentos.html#cb263-1"></a>contrast_specification &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>) </span>
<span id="cb263-2"><a href="análise-básica-de-dados-experimentos.html#cb263-2"></a></span>
<span id="cb263-3"><a href="análise-básica-de-dados-experimentos.html#cb263-3"></a><span class="co"># os quatro numeros correspondentes a b0, b1, b2, b3. </span></span>
<span id="cb263-4"><a href="análise-básica-de-dados-experimentos.html#cb263-4"></a><span class="co"># queremos testar se b1 eh significativo, entao colocamos 1 em 2º lugar (o 1º lugar é para b0)</span></span>
<span id="cb263-5"><a href="análise-básica-de-dados-experimentos.html#cb263-5"></a><span class="co">#contrast(linearmodel, contrast_specification)</span></span>
<span id="cb263-6"><a href="análise-básica-de-dados-experimentos.html#cb263-6"></a><span class="co">## </span></span>
<span id="cb263-7"><a href="análise-básica-de-dados-experimentos.html#cb263-7"></a><span class="co">## 	 Simultaneous Tests for General Linear Hypotheses</span></span>
<span id="cb263-8"><a href="análise-básica-de-dados-experimentos.html#cb263-8"></a><span class="co">## </span></span>
<span id="cb263-9"><a href="análise-básica-de-dados-experimentos.html#cb263-9"></a><span class="co">## Fit: aov(formula = linearmodel)</span></span>
<span id="cb263-10"><a href="análise-básica-de-dados-experimentos.html#cb263-10"></a><span class="co">## </span></span>
<span id="cb263-11"><a href="análise-básica-de-dados-experimentos.html#cb263-11"></a><span class="co">## Linear Hypotheses:</span></span>
<span id="cb263-12"><a href="análise-básica-de-dados-experimentos.html#cb263-12"></a><span class="co">##        Estimate Std. Error t value Pr(&gt;|t|)  </span></span>
<span id="cb263-13"><a href="análise-básica-de-dados-experimentos.html#cb263-13"></a><span class="co">## 1 == 0  -0.4501     0.2579  -1.745   0.0832 .</span></span>
<span id="cb263-14"><a href="análise-básica-de-dados-experimentos.html#cb263-14"></a><span class="co">## ---</span></span>
<span id="cb263-15"><a href="análise-básica-de-dados-experimentos.html#cb263-15"></a><span class="co">## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</span></span>
<span id="cb263-16"><a href="análise-básica-de-dados-experimentos.html#cb263-16"></a><span class="co">## (Adjusted p values reported -- single-step method)</span></span></code></pre></div>
<p>A saída nos diz que a estimativa do contraste é -0,45, que é realmente a diferença entre as médias observadas na condição privada (alta potência: 5,63 vs. baixa potência: 6,08). Você pode relatar esse resultado da seguinte forma: “O efeito de alta (M = 5,63, DP = 0,89) vs. baixa potência (M = 6,08, DP = 1,04) na condição privada foi marginalmente significativo (t (139) = -1,745 , p = 0,083).” Para obter os graus de liberdade, faça um contraste (linearmodel, contrast_specification)$df}</p>
<p>Digamos que queremos testar um contraste mais complicado, ou seja, se a média na célula privada de alta potência é diferente da média das médias nas outras células. Estamos testando:</p>
<p><span class="math inline">\((\beta_0 + \beta_1)-1/3*[(\beta_0)+(\beta_0 +\beta_2)+(\beta_0+\beta_1+\beta_2+\beta_3)]\)</span></p>
<p><span class="math inline">\(=\beta_1-1/3*(\beta_1+2\beta_2+\beta_3)\)</span></p>
<p><span class="math inline">\(=2/3 * \beta_1-2/3 * \beta_2-1/3 * \beta_3\)</span></p>
<p>A especificação de contraste é a seguinte:</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="análise-básica-de-dados-experimentos.html#cb264-1"></a>contrast_specification &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">2</span><span class="op">/</span><span class="dv">3</span>, <span class="dv">-2</span><span class="op">/</span><span class="dv">3</span>, <span class="dv">-1</span><span class="op">/</span><span class="dv">3</span>) </span>
<span id="cb264-2"><a href="análise-básica-de-dados-experimentos.html#cb264-2"></a><span class="co">#contrast(linearmodel, contrast_specification)</span></span>
<span id="cb264-3"><a href="análise-básica-de-dados-experimentos.html#cb264-3"></a><span class="co">## </span></span>
<span id="cb264-4"><a href="análise-básica-de-dados-experimentos.html#cb264-4"></a><span class="co">## 	 Simultaneous Tests for General Linear Hypotheses</span></span>
<span id="cb264-5"><a href="análise-básica-de-dados-experimentos.html#cb264-5"></a><span class="co">## </span></span>
<span id="cb264-6"><a href="análise-básica-de-dados-experimentos.html#cb264-6"></a><span class="co">## Fit: aov(formula = linearmodel)</span></span>
<span id="cb264-7"><a href="análise-básica-de-dados-experimentos.html#cb264-7"></a><span class="co">## </span></span>
<span id="cb264-8"><a href="análise-básica-de-dados-experimentos.html#cb264-8"></a><span class="co">## Linear Hypotheses:</span></span>
<span id="cb264-9"><a href="análise-básica-de-dados-experimentos.html#cb264-9"></a><span class="co">##        Estimate Std. Error t value Pr(&gt;|t|)  </span></span>
<span id="cb264-10"><a href="análise-básica-de-dados-experimentos.html#cb264-10"></a><span class="co">## 1 == 0  -0.4764     0.2109  -2.259   0.0254 *</span></span>
<span id="cb264-11"><a href="análise-básica-de-dados-experimentos.html#cb264-11"></a><span class="co">## ---</span></span>
<span id="cb264-12"><a href="análise-básica-de-dados-experimentos.html#cb264-12"></a><span class="co">## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</span></span>
<span id="cb264-13"><a href="análise-básica-de-dados-experimentos.html#cb264-13"></a><span class="co">## (Adjusted p values reported -- single-step method)</span></span></code></pre></div>
<p>Verifique se a estimativa realmente corresponde à diferença entre a média de alta potência, privada e a média das médias nas outras células. Você pode relatar o seguinte: “A célula privada de alta potência tinha uma WTP significativamente menor do que as outras células experimentais em nosso projeto (est = -0,476, t (139) = -2,259, p = 0,025)”.</p>
</div>
</div>
<div id="análise-de-moderação-interação-entre-variáveis-independentes-contínuas-e-categóricas" class="section level2 unlisted unnumbered">
<h2>Análise de moderação: interação entre variáveis independentes contínuas e categóricas</h2>
<p>Digamos que queremos testar se os resultados do experimento dependem do nível de domínio das pessoas. Em outras palavras, os efeitos do poder e da audiência são diferentes para participantes dominantes versus participantes não dominantes? Ainda em outras palavras, existe uma interação de três vias entre poder, audiência e domínio?</p>
<p>Vamos criar um gráfico primeiro:</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="análise-básica-de-dados-experimentos.html#cb265-1"></a><span class="co"># Nossa variavel dependente eh o consumo conspicuo, nossa variavel independente (no eixo X) eh a dominancia.</span></span>
<span id="cb265-2"><a href="análise-básica-de-dados-experimentos.html#cb265-2"></a><span class="co"># Entao, estamos tracando a relacao entre dominancia e consumo conspicuo.</span></span>
<span id="cb265-3"><a href="análise-básica-de-dados-experimentos.html#cb265-3"></a><span class="co"># O argumento da cor diz a R que queremos um relacionamento para cada nivel de poder.</span></span>
<span id="cb265-4"><a href="análise-básica-de-dados-experimentos.html#cb265-4"></a></span>
<span id="cb265-5"><a href="análise-básica-de-dados-experimentos.html#cb265-5"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> powercc, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> dominance, <span class="dt">y =</span> cc, <span class="dt">color =</span> power)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb265-6"><a href="análise-básica-de-dados-experimentos.html#cb265-6"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>audience) <span class="op">+</span><span class="st"> </span><span class="co"># Diga a R que tambem queremos dividir por audiencia.</span></span>
<span id="cb265-7"><a href="análise-básica-de-dados-experimentos.html#cb265-7"></a><span class="st">  </span><span class="kw">geom_jitter</span>() <span class="op">+</span><span class="st"> </span><span class="co"># Use geom_jitter em vez de geom_point, caso contrario, os pontos serao desenhados um sobre o outro</span></span>
<span id="cb265-8"><a href="análise-básica-de-dados-experimentos.html#cb265-8"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method=</span><span class="st">&#39;lm&#39;</span>, <span class="dt">se=</span><span class="ot">FALSE</span>) <span class="co"># Desenhe uma linha de regressao linear atraves dos pontos.</span></span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-127-1.png" width="672" /></p>
<p>Este gráfico é informativo. Isso nos mostra que, na condição privada, o efeito da alta versus baixa potência no consumo conspícuo é mais negativo para participantes menos dominantes do que para participantes mais dominantes. Na condição pública, o efeito da alta versus baixa potência no consumo conspícuo não difere entre os participantes menos versus os mais dominantes. Também vemos que, tanto na condição privada quanto na pública, os participantes mais vs. menos dominantes estão mais dispostos a gastar em consumo conspícuo.</p>
<p>Vamos verificar se a interação de três vias é significativa:</p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="análise-básica-de-dados-experimentos.html#cb267-1"></a>linearmodel &lt;-<span class="st"> </span><span class="kw">lm</span>(cc <span class="op">~</span><span class="st"> </span>power <span class="op">*</span><span class="st"> </span>audience <span class="op">*</span><span class="st"> </span>dominance, <span class="dt">data =</span> powercc)</span>
<span id="cb267-2"><a href="análise-básica-de-dados-experimentos.html#cb267-2"></a><span class="kw">type3anova</span>(linearmodel)</span></code></pre></div>
<pre><code>## # A tibble: 9 x 6
##   term                          ss   df1   df2       f pvalue
##   &lt;chr&gt;                      &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;  &lt;dbl&gt;
## 1 (Intercept)              525.        1   135 519.     0    
## 2 power                      2.21      1   135   2.18   0.142
## 3 audience                   0.715     1   135   0.706  0.402
## 4 dominance                 10.5       1   135  10.3    0.002
## 5 power:audience             1.44      1   135   1.42   0.235
## 6 power:dominance            1.18      1   135   1.17   0.282
## 7 audience:dominance         0.113     1   135   0.111  0.739
## 8 power:audience:dominance   1.30      1   135   1.29   0.258
## 9 Residuals                137.      135   135  NA     NA</code></pre>
<p>Somente o efeito da dominância é significativa. Se a interação de três vias fosse significativa, poderíamos acompanhar com mais testes. Por exemplo, poderíamos testar se a interação bidirecional entre dominância e poder é significativa na condição privada, como sugere o gráfico. Para fazer isso, vamos primeiro examinar os coeficientes de regressão do nosso modelo linear:</p>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="análise-básica-de-dados-experimentos.html#cb269-1"></a><span class="kw">summary</span>(linearmodel)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = cc ~ power * audience * dominance, data = powercc)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.58617 -0.63357  0.09751  0.68310  2.24067 
## 
## Coefficients:
##                                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                          5.7553     0.6019   9.561   &lt;2e-16 ***
## powerhigh                           -1.2490     0.7703  -1.621    0.107    
## audiencepublic                      -0.1651     0.6918  -0.239    0.812    
## dominance                            0.4526     0.7980   0.567    0.572    
## powerhigh:audiencepublic             1.1162     0.9355   1.193    0.235    
## powerhigh:dominance                  1.5021     1.1111   1.352    0.179    
## audiencepublic:dominance             0.5434     0.9514   0.571    0.569    
## powerhigh:audiencepublic:dominance  -1.5394     1.3561  -1.135    0.258    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.006 on 135 degrees of freedom
## Multiple R-squared:  0.1225,	Adjusted R-squared:  0.07703 
## F-statistic: 2.693 on 7 and 135 DF,  p-value: 0.01211</code></pre>
<p>Temos oito termos em nosso modelo:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> ou intercepto;</li>
<li><span class="math inline">\(\beta_1\)</span> ou o coeficiente para -“powerhigh”-</li>
<li><span class="math inline">\(\beta_2\)</span> ou o coeficiente para -“audiencepublic”-</li>
<li><span class="math inline">\(\beta_3\)</span> ou o coeficiente para -“dominance”-</li>
<li><span class="math inline">\(\beta_4\)</span> ou o coeficiente para -“powerhigh:audiencepublic”-</li>
<li><span class="math inline">\(\beta_5\)</span> ou o coeficiente para -“powerhigh:dominance”-</li>
<li><span class="math inline">\(\beta_6\)</span> ou o coeficiente para -“audiencepublic:dominance”-</li>
<li><span class="math inline">\(\beta_7\)</span> ou o coeficiente para -“powerhigh:audiencepublic:dominance”-</li>
</ul>
<p>Resultando nessa tabela de coeficientes:</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="análise-básica-de-dados-experimentos.html#cb271-1"></a><span class="co">#                     private                         public</span></span>
<span id="cb271-2"><a href="análise-básica-de-dados-experimentos.html#cb271-2"></a><span class="co"># low power          [b0] + (b3)                     [b0+b2] + (b3+b6)</span></span>
<span id="cb271-3"><a href="análise-básica-de-dados-experimentos.html#cb271-3"></a><span class="co"># high power         [b0+b1] + (b3+b5)               [b0+b1+b2+b4] + (b3+b5+b6+b7)</span></span></code></pre></div>
<p>Como conseguimos essa tabela? Com o modelo linear especificado acima, cada valor estimado de consumo conspícuo (a variável dependente) é uma função da condição experimental do participante e do nível de dominância do participante. Digamos que tenhamos um participante na condição pública de baixa potência com um nível de dominância de 0,5. O valor estimado do consumo conspícuo para esse participante é:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> ou intercepto x 1;</li>
<li><span class="math inline">\(\beta_1\)</span>  (porque o participante não está na condição de alta potência)</li>
<li><span class="math inline">\(\beta_2\)</span>  × 1 (na condição pública)</li>
<li><span class="math inline">\(\beta_3\)</span>  × 0.5 (dominance = 0.5)</li>
<li><span class="math inline">\(\beta_4\)</span>  × 0 (não no poder superior e na condição pública)</li>
<li><span class="math inline">\(\beta_5\)</span>  × 0 (não na condição de alta potência)</li>
<li><span class="math inline">\(\beta_6\)</span>  × 1 x 0,5 (na condição pública e dominância = 0,5)</li>
<li><span class="math inline">\(\beta_7\)</span>  × 0 (não no poder superior e na condição pública)</li>
</ul>
<p>ou</p>
<p><span class="math display">\[
\beta_0 \times 1 + \beta_1 \times 0 + \beta_2 \times 1 + \beta_3 \times 0.5 + \beta_4 \times 0 + \beta_5 \times 0 + \beta_6 \times 0.5 + \beta_7 \times 0
\]</span></p>
<p><span class="math inline">\(= [\beta_0 + \beta_2] + (\beta_3 + \beta_6) \times 0.5\)</span></p>
<p><span class="math inline">\(= [5.76 + -0.17] + (0.45 + 0.54) * 0.5 = 6.09\)</span></p>
<p>Verifique o gráfico para ver se isso realmente corresponde ao consumo conspícuo estimado de um participante com dominância = 0,5 na célula pública de baixa potência.</p>
<p>A fórmula geral para a célula pública de baixa potência é a seguinte:</p>
<p><span class="math display">\[
[\beta_0 + \beta_2] + (\beta_3 + \beta_6)\times\mbox{dominance}
\]</span></p>
<p>e podemos obter as fórmulas para as diferentes células de maneira semelhante. Vemos que em cada célula, o coeficiente entre colchetes é o valor estimado na medida de consumo conspícuo para um participante que pontua 0 em dominância. O coeficiente entre parênteses arredondados é o aumento estimado na medida de consumo conspícuo para cada aumento de uma unidade no domínio. Em outras palavras, os coeficientes entre colchetes representam a interceptação e os coeficientes entre colchetes representam a inclinação da linha que representa a regressão do consumo conspícuo (Y) na dominância (X) dentro de cada célula experimental (ou seja, cada potência e público-alvo) combinação).</p>
<p>Um teste da interação entre poder e dominância dentro da condição privada se resumiria a testar se as linhas azul e vermelha no painel esquerdo da figura acima devem ser consideradas paralelas ou não. Se eles são paralelos, o efeito da dominância no consumo conspícuo é o mesmo nas condições de baixa e alta potência. Se eles não são paralelos, o efeito da dominância é diferente nas condições de baixa e alta potência. Em outras palavras, devemos testar se os coeficientes de regressão são iguais dentro de baixa potência, privado e dentro de alta potência, privado. Em outras palavras, testamos se <span class="math inline">\((\beta_3+\beta_5)-\beta_3=\beta_5\)</span> é igual a zero:</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="análise-básica-de-dados-experimentos.html#cb272-1"></a><span class="co"># agora temos oito numeros correspondentes aos oito coeficientes de regressao</span></span>
<span id="cb272-2"><a href="análise-básica-de-dados-experimentos.html#cb272-2"></a><span class="co"># queremos testar se b5 eh significativo, entao colocamos 1 em 6º lugar (o 1º lugar é para b0)</span></span>
<span id="cb272-3"><a href="análise-básica-de-dados-experimentos.html#cb272-3"></a></span>
<span id="cb272-4"><a href="análise-básica-de-dados-experimentos.html#cb272-4"></a>contrast_specification &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb272-5"><a href="análise-básica-de-dados-experimentos.html#cb272-5"></a></span>
<span id="cb272-6"><a href="análise-básica-de-dados-experimentos.html#cb272-6"></a><span class="co">#contrast(linearmodel, contrast_specification)</span></span>
<span id="cb272-7"><a href="análise-básica-de-dados-experimentos.html#cb272-7"></a></span>
<span id="cb272-8"><a href="análise-básica-de-dados-experimentos.html#cb272-8"></a><span class="co">## </span></span>
<span id="cb272-9"><a href="análise-básica-de-dados-experimentos.html#cb272-9"></a><span class="co">##   Simultaneous Tests for General Linear Hypotheses</span></span>
<span id="cb272-10"><a href="análise-básica-de-dados-experimentos.html#cb272-10"></a><span class="co">## </span></span>
<span id="cb272-11"><a href="análise-básica-de-dados-experimentos.html#cb272-11"></a><span class="co">## Fit: aov(formula = linearmodel)</span></span>
<span id="cb272-12"><a href="análise-básica-de-dados-experimentos.html#cb272-12"></a><span class="co">## </span></span>
<span id="cb272-13"><a href="análise-básica-de-dados-experimentos.html#cb272-13"></a><span class="co">## Linear Hypotheses:</span></span>
<span id="cb272-14"><a href="análise-básica-de-dados-experimentos.html#cb272-14"></a><span class="co">##        Estimate Std. Error t value Pr(&gt;|t|)</span></span>
<span id="cb272-15"><a href="análise-básica-de-dados-experimentos.html#cb272-15"></a><span class="co">## 1 == 0    1.502      1.111   1.352    0.179</span></span>
<span id="cb272-16"><a href="análise-básica-de-dados-experimentos.html#cb272-16"></a><span class="co">## (Adjusted p values reported -- single-step method)</span></span></code></pre></div>
<p>A interação não é significativa, no entanto. Você pode relatar o seguinte: “Dentro da condição privada, não houve interação entre poder e dominância (t (135) = 1,352, p = 0,18).”</p>
<div id="análise-spotlight" class="section level3 unlisted unnumbered">
<h3>Análise <em>spotlight</em></h3>
<p>Em breve.</p>
</div>
</div>
<div id="análise-ancova" class="section level2 unlisted unnumbered">
<h2>Análise ANCOVA</h2>
<p>Descobrimos que nossas condições experimentais não afetam significativamente o consumo conspícuo:</p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb273-1"><a href="análise-básica-de-dados-experimentos.html#cb273-1"></a>linearmodel1 &lt;-<span class="st"> </span><span class="kw">lm</span>(cc <span class="op">~</span><span class="st"> </span>power<span class="op">*</span>audience, <span class="dt">data =</span> powercc)</span>
<span id="cb273-2"><a href="análise-básica-de-dados-experimentos.html#cb273-2"></a><span class="kw">type3anova</span>(linearmodel1)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 6
##   term                ss   df1   df2       f pvalue
##   &lt;chr&gt;            &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;  &lt;dbl&gt;
## 1 (Intercept)    5080.       1   139 4710.    0    
## 2 power             2.64     1   139    2.45  0.12 
## 3 audience          2.48     1   139    2.30  0.132
## 4 power:audience    1.11     1   139    1.03  0.313
## 5 Residuals       150.     139   139   NA    NA</code></pre>
<p>Por um lado, isso pode significar que simplesmente não há efeitos das condições experimentais no consumo conspícuo. Por outro lado, isso poderia significar que as manipulações experimentais não são fortes o suficiente ou que há muita variação inexplicada em nossa variável dependente (ou ambas). Podemos reduzir a variação inexplicável em nossa variável dependente, no entanto, incluindo uma variável em nosso modelo que suspeitamos estar relacionada à variável dependente. No nosso caso, suspeitamos que a disposição de gastar em consumo discreto (icc) esteja relacionada à disposição de gastar em consumo conspícuo. Embora icc seja uma variável contínua, podemos incluí-la como uma variável independente em nossa ANOVA e isso nos permitirá reduzir a variação inexplicável em nossa variável dependente:</p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb275-1"><a href="análise-básica-de-dados-experimentos.html#cb275-1"></a>linearmodel2 &lt;-<span class="st"> </span><span class="kw">lm</span>(cc <span class="op">~</span><span class="st"> </span>power<span class="op">*</span>audience <span class="op">+</span><span class="st"> </span>icc, <span class="dt">data =</span> powercc)</span>
<span id="cb275-2"><a href="análise-básica-de-dados-experimentos.html#cb275-2"></a><span class="kw">type3anova</span>(linearmodel2)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 6
##   term               ss   df1   df2      f pvalue
##   &lt;chr&gt;           &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1 (Intercept)    209.       1   138 221.    0    
## 2 power            1.88     1   138   1.99  0.16 
## 3 audience         1.14     1   138   1.21  0.274
## 4 icc             19.6      1   138  20.8   0    
## 5 power:audience   1.96     1   138   2.08  0.152
## 6 Residuals      130.     138   138  NA    NA</code></pre>
<p>Vemos que icc está relacionado à variável dependente e, portanto, que a soma dos quadrados dos resíduos desse modelo, ou seja, a variação inexplicada em nossa variável dependente, é menor (130,32) do que a do modelo sem icc (149,93). Os valores p dos fatores experimentais não diminuem, no entanto. Você pode relatar o seguinte: “Controlando a disposição de gastar em consumo discreto, nem o principal efeito do poder (F (1, 138) = 1,99, p = 0,16), nem o principal efeito do público (F (1, 138 ) = 1,21, p = 0,27), nem a interação entre poder e público (F (1, 138) = 2,08, p = 0,15) foi significativa.”</p>
<p>Chamamos essa análise de ANCOVA porque icc é uma covariável (abrange ou está relacionada à nossa variável dependente).</p>
</div>
<div id="medidas-repetidas-anova" class="section level2 unlisted unnumbered">
<h2>Medidas repetidas ANOVA</h2>
<p>Neste experimento, temos mais de uma medida por unidade de observação, ou seja, disposição para gastar em produtos conspícuos e disposição para gastar em produtos discretos. Uma ANOVA de medidas repetidas pode ser usada para testar se os efeitos das condições experimentais são diferentes para produtos conspícuos versus inconspícuos.</p>
<p>Para executar uma ANOVA de medidas repetidas, precisamos reestruturar nosso quadro de dados de amplo a longo. Um amplo quadro de dados possui uma linha por unidade de observação (em nosso experimento: uma linha por participante) e uma coluna por observação (em nosso experimento: uma coluna para os produtos conspícuos e uma coluna para os produtos inconspícuos). Um quadro de dados longo possui uma linha por observação (em nosso experimento: duas linhas por participante, uma linha para o produto conspícuo e uma linha para o produto inconspícuo) e uma coluna extra que indica com que tipo de observação estamos lidando (conspícua ou imperceptível). Vamos converter o quadro de dados e ver como os quadros de dados amplos e longos diferem um do outro.</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="análise-básica-de-dados-experimentos.html#cb277-1"></a><span class="kw">library</span>(tidyr)</span>
<span id="cb277-2"><a href="análise-básica-de-dados-experimentos.html#cb277-2"></a>powercc.long &lt;-<span class="st"> </span>powercc <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb277-3"><a href="análise-básica-de-dados-experimentos.html#cb277-3"></a><span class="st">  </span><span class="kw">gather</span>(consumption_type, wtp, cc, icc)</span>
<span id="cb277-4"><a href="análise-básica-de-dados-experimentos.html#cb277-4"></a></span>
<span id="cb277-5"><a href="análise-básica-de-dados-experimentos.html#cb277-5"></a><span class="co"># Converter de grande para longo significa que estamos empilhando varias colunas umas sobre as outras. Para isso, precisamos de uma variavel extra para acompanhar qual coluna estamos lidando.</span></span>
<span id="cb277-6"><a href="análise-básica-de-dados-experimentos.html#cb277-6"></a><span class="co"># A funcao de coleta converte conjuntos de dados de amplos para longos.</span></span>
<span id="cb277-7"><a href="análise-básica-de-dados-experimentos.html#cb277-7"></a><span class="co"># O primeiro argumento (consumer_type) nos dira com qual coluna estamos lidando. Essa eh a variavel que armazenara os nomes das colunas que estamos empilhando.</span></span>
<span id="cb277-8"><a href="análise-básica-de-dados-experimentos.html#cb277-8"></a><span class="co"># O segundo argumento (wtp) armazenara as colunas reais empilhadas umas sobre as outras.</span></span>
<span id="cb277-9"><a href="análise-básica-de-dados-experimentos.html#cb277-9"></a><span class="co"># Os argumentos a seguir sao as colunas que queremos empilhar.</span></span>
<span id="cb277-10"><a href="análise-básica-de-dados-experimentos.html#cb277-10"></a></span>
<span id="cb277-11"><a href="análise-básica-de-dados-experimentos.html#cb277-11"></a><span class="co"># Entao, dizemos ao gather para criar duas novas variaveis: tipo_de_consumo e vontade de pagar, para representar o empilhamento de um determinado numero de colunas.</span></span>
<span id="cb277-12"><a href="análise-básica-de-dados-experimentos.html#cb277-12"></a></span>
<span id="cb277-13"><a href="análise-básica-de-dados-experimentos.html#cb277-13"></a><span class="co"># Vamos dizer ao R para nos mostrar apenas as colunas relevantes (isto eh apenas para fins de apresentacao):</span></span>
<span id="cb277-14"><a href="análise-básica-de-dados-experimentos.html#cb277-14"></a></span>
<span id="cb277-15"><a href="análise-básica-de-dados-experimentos.html#cb277-15"></a>powercc.long <span class="op">%&gt;%</span></span>
<span id="cb277-16"><a href="análise-básica-de-dados-experimentos.html#cb277-16"></a><span class="st">  </span><span class="kw">select</span>(subject, power, audience, consumption_type, wtp) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb277-17"><a href="análise-básica-de-dados-experimentos.html#cb277-17"></a><span class="st">  </span><span class="kw">arrange</span>(subject)</span></code></pre></div>
<pre><code>## # A tibble: 286 x 5
##    subject power audience consumption_type   wtp
##    &lt;fct&gt;   &lt;fct&gt; &lt;fct&gt;    &lt;chr&gt;            &lt;dbl&gt;
##  1 1       high  public   cc                 5  
##  2 1       high  public   icc                2.6
##  3 2       low   public   cc                 7.6
##  4 2       low   public   icc                4  
##  5 3       low   public   cc                 5.4
##  6 3       low   public   icc                3.4
##  7 4       low   public   cc                 8.4
##  8 4       low   public   icc                5.2
##  9 5       high  public   cc                 7.8
## 10 5       high  public   icc                3  
## # ... with 276 more rows</code></pre>
<p>Temos duas linhas por assunto, uma coluna de disposição para pagar e outra coluna (tipo de consumo) que indica se está disposta a pagar por produtos visíveis ou imperceptíveis. Compare isso com o amplo conjunto de dados:</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="análise-básica-de-dados-experimentos.html#cb279-1"></a>powercc <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb279-2"><a href="análise-básica-de-dados-experimentos.html#cb279-2"></a><span class="st">  </span><span class="kw">select</span>(subject, power, audience, cc, icc) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb279-3"><a href="análise-básica-de-dados-experimentos.html#cb279-3"></a><span class="st">  </span><span class="kw">arrange</span>(subject) <span class="co"># Mostre somente as colunas relevantes</span></span></code></pre></div>
<pre><code>## # A tibble: 143 x 5
##    subject power audience    cc   icc
##    &lt;fct&gt;   &lt;fct&gt; &lt;fct&gt;    &lt;dbl&gt; &lt;dbl&gt;
##  1 1       high  public     5     2.6
##  2 2       low   public     7.6   4  
##  3 3       low   public     5.4   3.4
##  4 4       low   public     8.4   5.2
##  5 5       high  public     7.8   3  
##  6 6       high  public     7.2   5  
##  7 7       low   public     4.8   4  
##  8 8       high  public     6.6   4.4
##  9 9       low   public     5.8   4.2
## 10 10      high  public     6.8   3.4
## # ... with 133 more rows</code></pre>
<p>Temos uma linha por assunto e duas colunas, uma para cada tipo de produto.</p>
<p>Agora podemos realizar uma medida repetida ANOVA. Para isso, precisamos do pacote ez.</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="análise-básica-de-dados-experimentos.html#cb281-1"></a><span class="co">#install.packages(&quot;ez&quot;) # Precisamos do pacote ez para RM ANOVA</span></span>
<span id="cb281-2"><a href="análise-básica-de-dados-experimentos.html#cb281-2"></a><span class="kw">library</span>(ez)</span></code></pre></div>
<pre><code>## Registered S3 methods overwritten by &#39;lme4&#39;:
##   method                          from
##   cooks.distance.influence.merMod car 
##   influence.merMod                car 
##   dfbeta.influence.merMod         car 
##   dfbetas.influence.merMod        car</code></pre>
<p>Queremos testar se a interação entre poder e público é diferente para produtos conspícuos e inconspícuos. Vamos dar uma olhada em um gráfico primeiro:</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="análise-básica-de-dados-experimentos.html#cb283-1"></a>powercc.long.summary &lt;-<span class="st"> </span>powercc.long <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># para um grafico de barras precisamos de summary primeiro</span></span>
<span id="cb283-2"><a href="análise-básica-de-dados-experimentos.html#cb283-2"></a><span class="st">  </span><span class="kw">group_by</span>(power, audience, consumption_type) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># agrupa por tres variaveis independentes</span></span>
<span id="cb283-3"><a href="análise-básica-de-dados-experimentos.html#cb283-3"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">wtp =</span> <span class="kw">mean</span>(wtp)) <span class="co"># obtem a media de wtp</span></span></code></pre></div>
<pre><code>## `summarise()` regrouping output by &#39;power&#39;, &#39;audience&#39; (override with `.groups` argument)</code></pre>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="análise-básica-de-dados-experimentos.html#cb285-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> powercc.long.summary, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> audience, <span class="dt">y =</span> wtp, <span class="dt">fill =</span> power)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb285-2"><a href="análise-básica-de-dados-experimentos.html#cb285-2"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>consumption_type) <span class="op">+</span><span class="st"> </span><span class="co"># create a panel for each consumption type</span></span>
<span id="cb285-3"><a href="análise-básica-de-dados-experimentos.html#cb285-3"></a><span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="dt">position =</span> <span class="st">&quot;dodge&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-137-1.png" width="672" /></p>
<p>Agora podemos testar formalmente a interação de três vias:</p>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb286-1"><a href="análise-básica-de-dados-experimentos.html#cb286-1"></a><span class="co"># Especifique os dados, a variavel dependente, o identificador (wid),</span></span>
<span id="cb286-2"><a href="análise-básica-de-dados-experimentos.html#cb286-2"></a><span class="co"># a variavel que representa a condicao dentro dos sujeitos e as variaveis que representam as condicoes entre os sujeitos.</span></span>
<span id="cb286-3"><a href="análise-básica-de-dados-experimentos.html#cb286-3"></a></span>
<span id="cb286-4"><a href="análise-básica-de-dados-experimentos.html#cb286-4"></a><span class="kw">ezANOVA</span>(<span class="dt">data =</span> powercc.long, <span class="dt">dv =</span> wtp, <span class="dt">wid =</span> subject, <span class="dt">within =</span> consumption_type, <span class="dt">between =</span> power<span class="op">*</span>audience)</span></code></pre></div>
<pre><code>## Warning: You have removed one or more Ss from the analysis. Refactoring &quot;subject&quot; for
## ANOVA.</code></pre>
<pre><code>## Warning: Converting &quot;consumption_type&quot; to factor for ANOVA.</code></pre>
<pre><code>## Warning: Data is unbalanced (unequal N per group). Make sure you specified a well-
## considered value for the type argument to ezANOVA().</code></pre>
<pre><code>## $ANOVA
##                            Effect DFn DFd            F            p p&lt;.05          ges
## 2                           power   1 139 1.867530e+00 1.739647e-01       9.061619e-03
## 3                        audience   1 139 2.977018e+00 8.667716e-02       1.436772e-02
## 5                consumption_type   1 139 6.303234e+02 1.687352e-53     * 5.915501e-01
## 4                  power:audience   1 139 5.801046e-03 9.393977e-01       2.840440e-05
## 6          power:consumption_type   1 139 4.719313e-01 4.932445e-01       1.083172e-03
## 7       audience:consumption_type   1 139 2.700684e-02 8.697041e-01       6.204919e-05
## 8 power:audience:consumption_type   1 139 2.982598e+00 8.638552e-02       6.806406e-03</code></pre>
<p>Vemos nesses resultados que a interação de três vias entre poder, público e tipo de consumo é marginalmente significativa. Você pode relatar o seguinte: "Uma ANOVA de medidas repetidas estabeleceu que a interação de três vias entre poder, público e tipo de consumo era marginalmente significativa (F (1, 139) = 2,98, p = 0,086).</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="regressão-logística-opcional.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="análise-de-componentes-principais-para-mapas-perceptivos-office-dataset.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rhozon/rparamkt/edit/master/04-AnaliseBasicadedadosExperimentos.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/rhozon/rparamkt/blob/master/04-AnaliseBasicadedadosExperimentos.Rmd",
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
